version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '5300:5000'
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    depends_on:
      - backend
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
